=== lmarent/Auction_Engine/auction/xmls/auctionfile.dtd
<?xml version ="1.0" encoding="UTF-8"?>
<!-- The Document Type Definition (DTD) for the file -->

<!ELEMENT AUCTIONSET (GLOBAL, AUCTION*)>
<!ATTLIST AUCTIONSET
          ID CDATA #REQUIRED>

<!ELEMENT GLOBAL (ACTION|PREF)*>
<!-- global configuration is overruled by per auction configuration -->

<!ELEMENT AUCTION (ACTION, FIELD*,PREF*)>
<!ATTLIST AUCTION
        ID CDATA #REQUIRED
        RESOURCE_SET CDATA #REQUIRED
        RESOURCE_ID CDATA #REQUIRED >

<!ELEMENT PREF (#PCDATA)>
<!ATTLIST PREF
        NAME CDATA #REQUIRED
        TYPE (UInt8|SInt8|UInt16|SInt16|UInt32|SInt32|UInt64|SInt64|Bool|Binary|String|Float32|Float64) "String">

<!ELEMENT ACTION (PREF*)>
<!ATTLIST ACTION
        NAME CDATA #REQUIRED
        DEFAULT CDATA #REQUIRED >

<!ELEMENT FIELD (TEMPLATE_FIELD*)>
<!ATTLIST FIELD
        NAME CDATA #REQUIRED >

<!ELEMENT TEMPLATE_FIELD (#PCDATA)>
<!ATTLIST TEMPLATE_FIELD
        OBJECT_TYPE (BID|ASK|ALLOCATION)  #REQUIRED
        TEMPLATE_TYPE (DATA|OPTION)  #REQUIRED >

=== lmarent/Auction_Engine/auction/xmls/auction_two_auction_generalized.xml
<?xml version ="1.0" encoding="UTF-8"?>
<!DOCTYPE AUCTIONSET SYSTEM "auctionfile.dtd"> 
<!-- The Id must be an integer which represents the domain id-->
<AUCTIONSET ID="5">
  <!-- global part is the default for all auctions -->
  <!-- overwritten by rule specific configuration -->
  <GLOBAL>
    <!-- how long the auctions are active - value in seconds-->
    <PREF NAME="Duration">10000</PREF>

    <!-- How often they should be run - value in seconds -->
    <PREF NAME="Interval">30</PREF>
  </GLOBAL>
  <AUCTION ID="5" RESOURCE_SET="ResourceSet_1" RESOURCE_ID="router_1">
    <ACTION NAME="two_auction_generalized" DEFAULT="true">
    <PREF NAME="Bandwidth01" TYPE="Float32">10</PREF>
    <PREF NAME="Bandwidth02" TYPE="Float32">22</PREF>
    <PREF NAME="ReservePrice01" TYPE="Float64">0.15</PREF>
    <PREF NAME="ReservePrice02" TYPE="Float64">0.5</PREF>
    <PREF NAME="MaxValue01" TYPE="Float64">0.5</PREF>
    <PREF NAME="MaxValue02" TYPE="Float64">0.9</PREF>
    </ACTION>

	<FIELD NAME="quantity">
	<TEMPLATE_FIELD OBJECT_TYPE = "BID" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	<TEMPLATE_FIELD OBJECT_TYPE = "ALLOCATION" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	</FIELD>
    
	<FIELD NAME="unitprice">
	<TEMPLATE_FIELD OBJECT_TYPE = "BID" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	<TEMPLATE_FIELD OBJECT_TYPE = "ALLOCATION" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	</FIELD>

  </AUCTION>
</AUCTIONSET>

=== lmarent/Auction_Engine/auction/xmls/example_auctions1.xml
<?xml version ="1.0" encoding="UTF-8"?>
<!DOCTYPE AUCTIONSET SYSTEM "auctionfile.dtd">
<!-- The Id must be an integer which represents the domain id-->
<AUCTIONSET ID="1">
  <!-- global part is the default for all auctions -->
  <!-- overwritten by rule specific configuration -->
  <GLOBAL>
    <!-- how long the auctions are active - value in seconds-->
    <PREF NAME="Duration">100000</PREF>

    <!-- How often they should be run - value in seconds -->
    <PREF NAME="Interval">10</PREF>
  </GLOBAL>
  <AUCTION ID="10" RESOURCE_SET="1" RESOURCE_ID="router1">
    <ACTION NAME="libbas" DEFAULT="true"></ACTION>

	<FIELD NAME="quantity">
	<TEMPLATE_FIELD OBJECT_TYPE = "BID" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	<TEMPLATE_FIELD OBJECT_TYPE = "ALLOCATION" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	</FIELD>

	<FIELD NAME="unitbudget">
	<TEMPLATE_FIELD OBJECT_TYPE = "BID" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	</FIELD>

	<FIELD NAME="unitprice">
	<TEMPLATE_FIELD OBJECT_TYPE = "BID" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	<TEMPLATE_FIELD OBJECT_TYPE = "ALLOCATION" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	</FIELD>

	<FIELD NAME="biddingduration">
	<TEMPLATE_FIELD OBJECT_TYPE = "BID" TEMPLATE_TYPE = "OPTION"></TEMPLATE_FIELD>
	</FIELD>

  </AUCTION>
</AUCTIONSET>

=== lmarent/Auction_Engine/auction/xmls/example_auctions3.xml
<?xml version ="1.0" encoding="UTF-8"?>
<!DOCTYPE AUCTIONSET SYSTEM "auctionfile.dtd">
<!-- The Id must be an integer which represents the domain id-->
<AUCTIONSET ID="1">
  <!-- global part is the default for all auctions -->
  <!-- overwritten by rule specific configuration -->
  <GLOBAL>
    <!-- how long the auctions are active - value in seconds-->
    <PREF NAME="Duration">100000</PREF>

    <!-- How often they should be run - value in seconds -->
    <PREF NAME="Interval">10</PREF>
  </GLOBAL>
  <AUCTION ID="1" RESOURCE_SET="ResourceSet_1" RESOURCE_ID="Router_1">
    <ACTION NAME="basic_server_module" DEFAULT="true">
    <PREF NAME="Bandwidth" TYPE="Float32">8</PREF>
    <PREF NAME="ReservePrice" TYPE="Float64">0.0</PREF>
    </ACTION>

	<FIELD NAME="quantity">
	<TEMPLATE_FIELD OBJECT_TYPE = "BID" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	<TEMPLATE_FIELD OBJECT_TYPE = "ALLOCATION" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	</FIELD>

	<FIELD NAME="unitbudget">
	<TEMPLATE_FIELD OBJECT_TYPE = "BID" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	</FIELD>

	<FIELD NAME="unitprice">
	<TEMPLATE_FIELD OBJECT_TYPE = "BID" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	<TEMPLATE_FIELD OBJECT_TYPE = "ALLOCATION" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	</FIELD>

	<PREF NAME="Start">+10</PREF>
	<PREF NAME="Duration">100</PREF>

  </AUCTION>


  <AUCTION ID="2" RESOURCE_SET="ResourceSet_1" RESOURCE_ID="Router_1">
    <ACTION NAME="basic_server_module" DEFAULT="true">
    <PREF NAME="Bandwidth" TYPE="Float32">8</PREF>
    <PREF NAME="ReservePrice" TYPE="Float64">0.0</PREF>
    </ACTION>

	<FIELD NAME="quantity">
	<TEMPLATE_FIELD OBJECT_TYPE = "BID" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	<TEMPLATE_FIELD OBJECT_TYPE = "ALLOCATION" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	</FIELD>

	<FIELD NAME="unitbudget">
	<TEMPLATE_FIELD OBJECT_TYPE = "BID" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	</FIELD>

	<FIELD NAME="unitprice">
	<TEMPLATE_FIELD OBJECT_TYPE = "BID" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	<TEMPLATE_FIELD OBJECT_TYPE = "ALLOCATION" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	</FIELD>

	<PREF NAME="Start">+120</PREF>
	<PREF NAME="Duration">100</PREF>

  </AUCTION>


</AUCTIONSET>

=== lmarent/Auction_Engine/auction/xmls/auction_basic.xml
<?xml version ="1.0" encoding="UTF-8"?>
<!DOCTYPE AUCTIONSET SYSTEM "auctionfile.dtd"> 
<!-- The Id must be an integer which represents the domain id-->
<AUCTIONSET ID="1">
  <!-- global part is the default for all auctions -->
  <!-- overwritten by rule specific configuration -->
  <GLOBAL>
    <!-- how long the auctions are active - value in seconds-->
    <PREF NAME="Duration">10000</PREF>

    <!-- How often they should be run - value in seconds -->
    <PREF NAME="Interval">30</PREF>
  </GLOBAL>
  <AUCTION ID="1" RESOURCE_SET="ResourceSet_1" RESOURCE_ID="router_1">
    <ACTION NAME="basic_module" DEFAULT="true">
    <PREF NAME="Bandwidth" TYPE="Float32">32</PREF>
    <PREF NAME="ReservePrice" TYPE="Float64">0</PREF>
    </ACTION>

	<FIELD NAME="quantity">
	<TEMPLATE_FIELD OBJECT_TYPE = "BID" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	<TEMPLATE_FIELD OBJECT_TYPE = "ALLOCATION" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	</FIELD>
    
	<FIELD NAME="unitprice">
	<TEMPLATE_FIELD OBJECT_TYPE = "BID" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	<TEMPLATE_FIELD OBJECT_TYPE = "ALLOCATION" TEMPLATE_TYPE = "DATA"></TEMPLATE_FIELD>
	</FIELD>

  </AUCTION>
</AUCTIONSET>
