=== lmarent/Auction_Engine/auction/xmls/bidfile.dtd
<?xml version ="1.0" encoding="UTF-8"?>
<!-- The Document Type Definition (DTD) for the file -->

<!ELEMENT BIDDING_OBJECT_SET (BIDDING_OBJECT*)>
<!ATTLIST BIDDING_OBJECT_SET
          ID CDATA #REQUIRED>

<!ELEMENT BIDDING_OBJECT (ELEMENT|OPTION)*>
<!ATTLIST BIDDING_OBJECT
        AUCTION_ID CDATA #REQUIRED
        ID CDATA #REQUIRED
        TYPE (BID|ASK|ALLOCATION) #REQUIRED >

<!ELEMENT FIELD (#PCDATA)>
<!ATTLIST FIELD
        NAME CDATA #REQUIRED
        TYPE (UInt8|SInt8|UInt16|SInt16|UInt32|SInt32|UInt64|SInt64|Bool|Binary|String|Float|Double|IPAddr|IP6Addr) "String">

<!ELEMENT ELEMENT (FIELD*)>
<!ATTLIST ELEMENT
        ID CDATA #REQUIRED>

<!ELEMENT OPTION (PREF*) >
<!ATTLIST OPTION
        ID CDATA #REQUIRED  >

<!ELEMENT PREF (#PCDATA)>
<!ATTLIST PREF
        NAME CDATA #REQUIRED
        TYPE (UInt8|SInt8|UInt16|SInt16|UInt32|SInt32|UInt64|SInt64|Bool|Binary|String|Float|Double|IPAddr|IP6Addr) "String">

=== lmarent/Auction_Engine/auction/xmls/example_bids1.xml
<?xml version ="1.0" encoding="UTF-8"?>
<!DOCTYPE BIDDING_OBJECT_SET SYSTEM "bidfile.dtd">
<BIDDING_OBJECT_SET ID = "1">

  <BIDDING_OBJECT AUCTION_ID="1.1" ID="Bid1" TYPE="BID">

	<ELEMENT ID="element1">
		<FIELD NAME="quantity">1</FIELD>
		<FIELD NAME="unitbudget">0.14</FIELD>
		<FIELD NAME="unitprice">0.15</FIELD>
	</ELEMENT>

	<ELEMENT ID="element2">
		<FIELD NAME="quantity">2</FIELD>
		<FIELD NAME="unitbudget">0.13</FIELD>
		<FIELD NAME="unitprice">0.16</FIELD>
	</ELEMENT>

    <OPTION ID="option1">
		<PREF NAME="BiddingDuration">600</PREF>
    </OPTION>

    <OPTION ID="option2">
		<PREF NAME="BiddingDuration">60</PREF>
    </OPTION>


  </BIDDING_OBJECT>
</BIDDING_OBJECT_SET>
