=== lmarent/Auction_Engine/auction/xmls/resourcerequestfile.dtd
<?xml version ="1.0" encoding="UTF-8"?>
<!-- The Document Type Definition (DTD) for the file -->

<!ELEMENT RESOURCE_REQUEST_SET (RESOURCE_REQUEST*)>
<!ATTLIST RESOURCE_REQUEST_SET
          ID CDATA #REQUIRED>

<!ELEMENT RESOURCE_REQUEST (FIELD|INTERVAL)*>
<!ATTLIST RESOURCE_REQUEST
        ID CDATA #REQUIRED>

<!ELEMENT FIELD (#PCDATA)>
<!ATTLIST FIELD
        NAME CDATA #REQUIRED
        TYPE (UInt8|SInt8|UInt16|SInt16|UInt32|SInt32|UInt64|SInt64|Bool|Binary|String|Float32|Float64) "String">

<!ELEMENT INTERVAL (PREF*)>
<!ATTLIST INTERVAL
        NAME CDATA #REQUIRED>

<!ELEMENT PREF (#PCDATA)>
<!ATTLIST PREF
        NAME CDATA #REQUIRED
        TYPE (UInt8|SInt8|UInt16|SInt16|UInt32|SInt32|UInt64|SInt64|Bool|Binary|String) "String">

=== lmarent/Auction_Engine/auction/xmls/test3_two_auction_generalized.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE RESOURCE_REQUEST_SET PUBLIC "SYSTEM" "resourcerequestfile.dtd">
<RESOURCE_REQUEST_SET ID="UNIQUE">

    <RESOURCE_REQUEST ID="SET1_202_207_26">
        <FIELD NAME="quantity">6</FIELD>
        <FIELD NAME="totalbudget">0.612</FIELD>
        <FIELD NAME="maxvalue">0.635</FIELD>
        <FIELD NAME="DstIPV4">8.8.8.8</FIELD>
        <FIELD NAME="DstPort">80</FIELD>
        <INTERVAL NAME="interval1">
            <PREF NAME="Start">+10</PREF>
            <PREF NAME="Duration">228</PREF>
        </INTERVAL>
    </RESOURCE_REQUEST>

    <RESOURCE_REQUEST ID="SET1_202_149_11">
        <FIELD NAME="quantity">3</FIELD>
        <FIELD NAME="totalbudget">0.794</FIELD>
        <FIELD NAME="maxvalue">0.281</FIELD>
        <FIELD NAME="DstIPV4">8.8.8.8</FIELD>
        <FIELD NAME="DstPort">80</FIELD>
        <INTERVAL NAME="interval1">
            <PREF NAME="Start">+10</PREF>
            <PREF NAME="Duration">83</PREF>
        </INTERVAL>

        <INTERVAL NAME="interval2">
            <PREF NAME="Start">+200</PREF>
            <PREF NAME="Duration">83</PREF>
        </INTERVAL>

    </RESOURCE_REQUEST>

    <RESOURCE_REQUEST ID="SET1_239_137_20">
        <FIELD NAME="quantity">6</FIELD>
        <FIELD NAME="totalbudget">0.791</FIELD>
        <FIELD NAME="maxvalue">0.75</FIELD>
        <FIELD NAME="DstIPV4">8.8.8.8</FIELD>
        <FIELD NAME="DstPort">80</FIELD>
        <INTERVAL NAME="interval1">
            <PREF NAME="Start">+10</PREF>
            <PREF NAME="Duration">200</PREF>
        </INTERVAL>

        <INTERVAL NAME="interval2">
            <PREF NAME="Start">+300</PREF>
            <PREF NAME="Duration">83</PREF>
        </INTERVAL>


    </RESOURCE_REQUEST>


</RESOURCE_REQUEST_SET>

=== lmarent/Auction_Engine/auction/xmls/example_resource_request1.xml
<?xml version ="1.0" encoding="UTF-8"?>
<!DOCTYPE RESOURCE_REQUEST_SET SYSTEM "resourcerequestfile.dtd">
<RESOURCE_REQUEST_SET ID="Set1">

  <RESOURCE_REQUEST ID="1">
	<FIELD NAME="quantity">2</FIELD>
	<FIELD NAME="totalbudget">0.3</FIELD>
	<FIELD NAME="maxvalue">0.16</FIELD>
	<FIELD NAME="DstIP">8.8.8.8</FIELD>
	<FIELD NAME="DstPort">80</FIELD>
	<INTERVAL NAME="interval1">
		<!-- Duration  -->
		<PREF NAME="Duration">100</PREF>
    </INTERVAL>
	<INTERVAL NAME="interval2">
		<!-- Duration  -->
		<PREF NAME="Duration">100</PREF>
    </INTERVAL>

  </RESOURCE_REQUEST>

</RESOURCE_REQUEST_SET>
